version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "0.0.0.0:27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    command: mongod --bind_ip_all

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "0.0.0.0:8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password123@mongodb:27017/
    networks:
      - mongodb_network
    depends_on:
      - mongodb

volumes:
  mongodb_data:

networks:
  mongodb_network:
    driver: bridge 