version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "0.0.0.0:27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    command: mongod --bind_ip_all

volumes:
  mongodb_data:

networks:
  mongodb_network:
    driver: bridge 